version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mastra-postgres
    environment:
      POSTGRES_USER: mastra
      POSTGRES_PASSWORD: mastra_password
      POSTGRES_DB: mastra_memory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app-db:
    image: postgres:16-alpine
    container_name: app-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobs
    ports:
      - "5433:5432"
    volumes:
      - app_postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  app_postgres_data:
